### PR TITLE
report to posit-connect-tools snyk org

### PR DESCRIPTION
**Pull request by christierney**
We don't want this included in the main Connect SBOM as it is a separate tool.

https://positpbc.atlassian.net/wiki/spaces/INF/pages/995393738/Quarterly+Snyk+Org+Checklist+-+SBOM+Creation

### CODE REVIEW

**Comment by christierney** [comment]
@mmarchetti we will also need to update the `SNYK_TOKEN` secret. I have the new token but don't have access on this repo to change secrets.

**Review by tdstein — APPROVED** [review]
Looks good. Does GA support workflow dispatch on a pull request yet?

**Comment by christierney** [comment]
> Looks good. Does GA support workflow dispatch on a pull request yet?

it does, _if_ the workflow has previously been run on main (so, it is available for this one)

**Comment by christierney** [comment]
2a0aa318-c505-4d49-87e7-2b6ab401a887

**Comment by christierney** [comment]
https://github.com/posit-dev/rsconnect-python/actions/runs/10742631699

**Pull request merged**
